### ISSUE TITLE
I implemented naive Bayes code and Everytime I enter the inputs it gives the same output as hurray no heart disease

### ISSUE THREAD

**Issue by ghost** [iKhushPatel/Heart-Disease-Prediction#1]

**Comment by iKhushPatel** [comment]
![Image](https://user-images.githubusercontent.com/9557357/81597250-73c53100-9393-11ea-8fa1-9186b6183420.JPG)

Check here, It will also give if you have Heart Problem. Let me know if you need any other comments.

**Comment by ghost** [comment]
[image: image.png]

Hello Sir,
I am very grateful to you that you replied, I inserted the same inputs that
you have shared but then also getting the same error.

**Comment by iKhushPatel** [comment]
Can you share any screenshot so I can get the error? I hope so you are entering values in non-capital letters as mentioned in the upper image.

**Comment by ghost** [comment]
Untitled4.ipynb
<https://drive.google.com/file/d/1WUMsGD3VPZzM11x-5j_I3-lzrPs4M36c/view?usp=drive_web>
I am sharing the  code file and output screenshot . I have entered the same
values which u had shared with me but then also getting the same error.

**Comment by ghost** [comment]
I've shared an item with you:

Untitled4.ipynb
https://colab.research.google.com/drive/1WUMsGD3VPZzM11x-5j_I3-lzrPs4M36c?invite=CIf3ztsH&ts=5ebc260f

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

sharing the code
